package com.alon.pruebasGDX.girarrodillos.utils.events;

public enum EventType {
    GAME_INITIALIZED,
    HERO_ACTION,
    PLAYER_TURN_START,
    PLAYER_TURN_END,
    WHEELS_SPIN_START,
    WHEELS_SPIN_END,
    CROWN_HEALED,
    HERO_HELPED,
    HERO_DELAYED,
    BASTION_BOOST,
    OPPONENT_TURN_END,
    HERO_HELP,
    ACTION_EXECUTED, CROWN_DAMAGED, BASTION_DAMAGED, HERO_ENERGY_CHANGED, HERO_EXPERIENCE_CHANGED, HERO_EVOLVED, BOMB_CREATED, OPPONENT_TURN_START
}
